### ISSUE TITLE
被封号了

### ISSUE THREAD

**Issue by kikilau** [PatientDesperate/jyt-boot#1]
用了一下，微信号被封了，只能现场挂号，不知道怎么解除，还是一直给封了。

**Comment by likefrank** [comment]
不敢用了

**Comment by iBreaker** [comment]
> 用了一下，微信号被封了，只能现场挂号，不知道怎么解除，还是一直给封了。

可以试试这个  https://github.com/iBreaker/bjguahao

**Comment by kikilau** [comment]
> 不敢用了

后来我提交身份证 ，人工审核给我解除了，还告诉我不要非法刷票。

**Comment by kikilau** [comment]
> > 用了一下，微信号被封了，只能现场挂号，不知道怎么解除，还是一直给封了。
> 
> 可以试试这个 https://github.com/iBreaker/bjguahao

嗯嗯，那个号只能在京医通上，没办法。

**Comment by vvcit** [comment]
是的，我也被封了，刚挂上一个号，马上被封了- -

**Comment by iBreaker** [comment]
![image](https://user-images.githubusercontent.com/3455675/59831668-d1fcb600-9374-11e9-9723-cff64e58a7f8.png)
